name: Main

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    if: ${{ false }}
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn setup && yarn workspace @ensdomains/thorin build

  lint:
    if: ${{ false }}
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Check types
        run: yarn lint:types

  test:
    if: ${{ false }}
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test --coverage
